#include QMK_KEYBOARD_H

#include "keymap_danish.h"

#define _MAC 0
#define _UBUNTU 1
#define _F 2
#define _FUNC 3

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_MAC] = LAYOUT_65_iso(LT(_FUNC, KC_ESC), DK_1, DK_2, DK_3, DK_4, DK_5, DK_6, DK_7, DK_8, DK_9, DK_0, DK_PLUS, DK_ACUT, KC_BSPC, LGUI(KC_SPC), KC_TAB, DK_Q, DK_W, DK_E, DK_R, DK_T, DK_Y, DK_U, DK_I, DK_O, DK_P, DK_ARNG, DK_DIAE, LSFT(LCTL(LGUI(KC_H))), TG(_UBUNTU), DK_A, DK_S, DK_D, DK_F, DK_G, DK_H, DK_J, DK_K, DK_L, DK_AE, DK_OSTR, DK_QUOT, KC_ENT, LSFT(LCTL(LGUI(KC_4))), KC_LSFT, DK_LABK, DK_Z, DK_X, DK_C, DK_V, DK_B, DK_N, DK_M, DK_COMM, DK_DOT, KC_SLSH, KC_RSFT, KC_UP, LCTL(LGUI(KC_SPC)), KC_LCTL, KC_LALT, KC_LGUI, KC_SPC, KC_RGUI, LT(_F, KC_ESC), KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),

    [_UBUNTU] = LAYOUT_65_iso(LT(_FUNC, KC_ESC), DK_1, DK_2, DK_3, DK_4, DK_5, DK_6, DK_7, DK_8, DK_9, DK_0, DK_PLUS, DK_ACUT, KC_BSPC, KC_GRV, KC_TAB, DK_Q, DK_W, DK_E, DK_R, DK_T, DK_Y, DK_U, DK_I, DK_O, DK_P, DK_ARNG, DK_DIAE, KC_DEL, KC_TRNS, DK_A, DK_S, DK_D, DK_F, DK_G, DK_H, DK_J, DK_K, DK_L, DK_AE, DK_OSTR, DK_QUOT, KC_ENT, KC_PGUP, KC_LSFT, DK_LABK, DK_Z, DK_X, DK_C, DK_V, DK_B, DK_N, DK_M, DK_COMM, DK_DOT, KC_SLSH, KC_RSFT, KC_UP, KC_PGDN, KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_RALT, KC_RGUI, KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),

    [_F] = LAYOUT_65_iso(KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    [_FUNC] = LAYOUT_65_iso(KC_TRNS, KC_BRMD, KC_BRMU, KC_F3, KC_F4, KC_F5, KC_F6, KC_MEDIA_PREV_TRACK, KC_MEDIA_PLAY_PAUSE, KC_MEDIA_NEXT_TRACK, KC__MUTE, KC__VOLDOWN, KC__VOLUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)};
